language: ruby
services:
  - mysql
install:
  — bundle install
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec/
before_install:
  - mysql -e 'CREATE DATABASE lunch_ordering_test;'
before_script:
  - cp config/database.travis.yml config/database.yml
